using MediatR;
using Microsoft.EntityFrameworkCore;
using PosBackend.Application.Common.Interfaces;

namespace PosBackend.Application.Reports;

/// <summary>
/// Data transfer object carrying aggregated revenue information for a single day.
/// </summary>
/// <param name="Date">The calendar date of the record.</param>
/// <param name="SaleCount">The number of individual sales transactions settled on this date.</param>
/// <param name="TotalRevenue">The sum total revenue accumulated on this date.</param>
public sealed record DailyRevenueDto(DateOnly Date, int SaleCount, decimal TotalRevenue);

/// <summary>
/// Data transfer object carrying transaction totals for a product.
/// </summary>
/// <param name="ProductId">Unique identifier of the product.</param>
/// <param name="ProductName">Name of the product.</param>
/// <param name="QuantitySold">Total quantity units sold.</param>
/// <param name="Revenue">Total revenue generated by sales of this product.</param>
public sealed record TopProductDto(Guid ProductId, string ProductName, int QuantitySold, decimal Revenue);

/// <summary>
/// Query to retrieve daily revenue aggregation within an optional date range.
/// </summary>
/// <param name="From">Optional starting date boundary (inclusive).</param>
/// <param name="To">Optional ending date boundary (inclusive).</param>
public sealed record GetDailyRevenueQuery(DateOnly? From = null, DateOnly? To = null) : IRequest<IReadOnlyList<DailyRevenueDto>>;

/// <summary>
/// Query to retrieve the top performing products based on units sold.
/// </summary>
/// <param name="Limit">The maximum number of products to return (between 1 and 100).</param>
/// <param name="From">Optional starting timestamp boundary (inclusive).</param>
/// <param name="To">Optional ending timestamp boundary (inclusive).</param>
public sealed record GetTopProductsQuery(int Limit = 10, DateTime? From = null, DateTime? To = null) : IRequest<IReadOnlyList<TopProductDto>>;

/// <summary>
/// Consolidated MediatR handlers for shop performance and inventory reports.
/// </summary>
public sealed class ReportHandlers :
    IRequestHandler<GetDailyRevenueQuery, IReadOnlyList<DailyRevenueDto>>,
    IRequestHandler<GetTopProductsQuery, IReadOnlyList<TopProductDto>>
{
    private readonly IAppDbContext _dbContext;
    private readonly ICurrentUserService _currentUserService;

    /// <summary>
    /// Initializes a new instance of the <see cref="ReportHandlers"/> class.
    /// </summary>
    /// <param name="dbContext">The application database context.</param>
    /// <param name="currentUserService">The service providing the authenticated user and store context.</param>
    public ReportHandlers(IAppDbContext dbContext, ICurrentUserService currentUserService)
    {
        _dbContext = dbContext;
        _currentUserService = currentUserService;
    }

    /// <summary>
    /// Handles daily revenue queries for the active store. Groups sale transaction total amounts by calendar date.
    /// </summary>
    public async Task<IReadOnlyList<DailyRevenueDto>> Handle(GetDailyRevenueQuery request, CancellationToken cancellationToken)
    {
        var storeId = _currentUserService.StoreId;

        var salesQuery = _dbContext.Sales
            .AsNoTracking()
            .Where(sale => sale.StoreId == storeId)
            .AsQueryable();

        // Apply starting boundary filter.
        // Convert DateOnly to a UTC DateTime representing the start of that day.
        if (request.From.HasValue)
        {
            var startDateTimeUtc = request.From.Value.ToDateTime(TimeOnly.MinValue, DateTimeKind.Utc);
            salesQuery = salesQuery.Where(sale => sale.CreatedAt >= startDateTimeUtc);
        }

        // Apply ending boundary filter.
        // Add 1 day to make the filter inclusive of the specified day (up to the very beginning of the next day).
        if (request.To.HasValue)
        {
            var endDateTimeUtc = request.To.Value.AddDays(1).ToDateTime(TimeOnly.MinValue, DateTimeKind.Utc);
            salesQuery = salesQuery.Where(sale => sale.CreatedAt < endDateTimeUtc);
        }

        // Group sales by their calendar date and sum up transactions.
        return await salesQuery
            .GroupBy(sale => DateOnly.FromDateTime(sale.CreatedAt))
            .OrderBy(group => group.Key)
            .Select(group => new DailyRevenueDto(
                group.Key,
                group.Count(),
                group.Sum(sale => sale.TotalAmount)))
            .ToListAsync(cancellationToken);
    }

    /// <summary>
    /// Handles top performing products query for the active store. Groups sold items by product ID and aggregates volumes/revenue.
    /// </summary>
    public async Task<IReadOnlyList<TopProductDto>> Handle(GetTopProductsQuery request, CancellationToken cancellationToken)
    {
        var storeId = _currentUserService.StoreId;

        var saleItemsQuery = _dbContext.SaleItems
            .AsNoTracking()
            .Where(item => item.Sale!.StoreId == storeId)
            .AsQueryable();

        // Apply starting date range boundaries.
        if (request.From.HasValue)
        {
            saleItemsQuery = saleItemsQuery.Where(item => item.Sale!.CreatedAt >= request.From.Value.ToUniversalTime());
        }

        // Apply ending date range boundaries.
        if (request.To.HasValue)
        {
            saleItemsQuery = saleItemsQuery.Where(item => item.Sale!.CreatedAt <= request.To.Value.ToUniversalTime());
        }

        // Aggregate units sold and revenue by ProductId.
        var aggregatedSales = await saleItemsQuery
            .GroupBy(item => item.ProductId)
            .Select(group => new
            {
                ProductId = group.Key,
                QuantitySold = group.Sum(item => item.Quantity),
                Revenue = group.Sum(item => item.Subtotal)
            })
            .OrderByDescending(aggregate => aggregate.QuantitySold)
            .Take(Math.Clamp(request.Limit, 1, 100))
            .ToListAsync(cancellationToken);

        // Fetch product names for the aggregated product list.
        var productIds = aggregatedSales.Select(aggregate => aggregate.ProductId).ToList();
        var productNamesMap = await _dbContext.Products
            .AsNoTracking()
            .Where(product => productIds.Contains(product.Id) && product.StoreId == storeId)
            .ToDictionaryAsync(product => product.Id, product => product.Name, cancellationToken);

        // Map aggregated records to TopProductDto, sorting by quantity units sold descending, then alphabetically.
        return aggregatedSales
            .Select(aggregate => new TopProductDto(
                aggregate.ProductId,
                productNamesMap.GetValueOrDefault(aggregate.ProductId) ?? string.Empty,
                aggregate.QuantitySold,
                aggregate.Revenue))
            .OrderByDescending(dto => dto.QuantitySold)
            .ThenBy(dto => dto.ProductName)
            .ToList();
    }
}
